#!/bin/bash
set -eu
echo purging images...
N=${1:-1000}
for n in $(seq 0 $N)
do
  printf -- "$n\n" 
  docker image inspect wyga-deploy-test:$n &>/dev/null &&  docker image rm wyga-deploy-test:$n || true
done
