#!/bin/bash
set -eu
export DOCKER_BUILDER="multiplatform-builder"
docker run --quiet --privileged --rm tonistiigi/binfmt --install all &>/dev/null
docker buildx inspect "${DOCKER_BUILDER}" --bootstrap || docker buildx create --use --bootstrap --name "${DOCKER_BUILDER}"
